### PR TITLE
Fixing bug with messages inside other processes

### LINKED ISSUE #10: Testing messages received from inside another spawned process
It appears that something like this doesn't work correctly.  

```
test "this will fail because the message is sent to the spawned process" do
  inject = double |> allow(:some_function, with: [], returns: :ok)
  test_me()
  assert_receive :some_function
end

defp test_me(inject) do
  spawn fn ->
    inject.some_function.()
  end
end
```

### PR DESCRIPTION
**Pull request by brandonjoyce**
This resolves an issue where double is receiving function calls from inside a process separate from the test process. 

Resolves #10 

```elixir
test "this will work now" do
  inject = double |> allow(:some_function, with: [], returns: :ok)
  spawn fn ->
    inject.some_function.()
  end
  assert_receive :some_function
end
```

### CODE REVIEW

**Comment by grosscr** [comment]
👍

File: lib/double/registry.ex [hunk 1]
```diff
@@ -23,13 +27,23 @@ defmodule Double.Registry do
   end
 
   def handle_call({:whereis_double, double_id}, _from, state) do
-    {:reply, Map.get(state, double_id, :undefined), state}
+    double_pid = state
+    |> Map.get(double_id, {:undefined, nil})
+    |> elem(0)
```
Comment (ringmaster) [inline lib/double/registry.ex]: Can't do this?:
```Elixir
{double_pid,_} = state
|> Map.get(double_id, {:undefined, nil})
```

Comment (brandonjoyce) [reply lib/double/registry.ex]: Sure can.  I'll change it.
